# Generated by Django 2.2.9 on 2020-11-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_id', models.IntegerField()),
                ('name', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.TextField(default='RUB', max_length=3)),
                ('create_date', models.DateTimeField()),
                ('qr_id', models.TextField(max_length=32)),
                ('qr_url', models.TextField()),
                ('payment_state', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('nickname', models.TextField()),
                ('account', models.TextField()),
                ('token', models.TextField()),
                ('min_donation', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
