# Generated by Django 2.2.9 on 2020-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0002_auto_20201114_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donat',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
