# Generated by Django 2.2.9 on 2020-11-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0004_auto_20201114_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donat',
            name='text',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
