# Generated by Django 2.2.9 on 2020-11-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamer', '0005_auto_20201114_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='donat',
            name='is_shown',
            field=models.IntegerField(default=0),
        ),
    ]
